### PR TITLE
Updated versions to Vaadin Spring 1.2.0 and Spring Boot 1.5.1

### PR DESCRIPTION
**Pull request by mstahv**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mstahv Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-crud-with-vaadin&pullRequestId=7)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-crud-with-vaadin&pullRequestId=7) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by mstahv** [comment]
Oh those CLAs, I should have just pushed it in as I think I have the commit right :-) @gregturn just wanted you to give a quick look on it, 1.2.0 form Vaadin Spring works with Spring Boot 1.5 series.

The CLA should be now ok.

**Comment by gregturn** [comment]
@mstahv Thanks for making the update. 

Sorry about the CLA. I promise this is about as smooth as I've seen any CLA. And it's Spring-wide, meaning you only have to sign it once for ALL Spring portfolio projects.

**Comment by mstahv** [comment]
NP. And it sure was smooth, but for some reason the status don't seem to update to this issue.

**Comment by gregturn** [comment]
Okay, we'll watch it with the next PR. ?!?!

**Comment by mstahv** [comment]
Yep, I'll start preparing Vaadin 8 version of the guide soon so we can push that out ASAP after the final release (Vaadin 8 is out "any week now").

**Pull request merged**
